server:
  port: 8888

management:
  context-path: /admin
  
logging:
  level:
    org.springframework.cloud: 'DEBUG'
    
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:./steeltoe/config-repo
#
# Replace spring: configuration above with what is below for github repo usage
#
# spring:
#   cloud:
#     config:
#       server:
#         git: https://github.com/SteeltoeOSS/workshop-config-repo.git